# Netlify Configuration for Vikas Sahu Portfolio

[build]
  base = "frontend"
  publish = "dist/frontend-app/browser"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
